///**
// * NOTE: This class is auto generated by the server code generator program (2.2.3).
// * https://github.com/swagger-api/swagger-codegen
// * Do not edit the class manually.
// */
//package park.server.api;
//
//import park.server.model.Status;
//
//import io.swagger.annotations.*;
//import org.springframework.http.ResponseEntity;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//
//public interface ServiceApi {
//
//    @ApiOperation(value = "Очистка всех данных в базе", notes = "Безвозвратное удаление всей пользовательской информации из базы данных. ", response = Void.class, tags={  })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "Очистка базы успешно завершена", response = Void.class) })
//
//    @RequestMapping(value = "/service/clear",
//        produces = { "application/json" },
//        consumes = { "application/json", "application/octet-stream" },
//        method = RequestMethod.POST)
//    ResponseEntity<Void> clear();
//
//
//    @ApiOperation(value = "Получение инфомарции о базе данных", notes = "Получение инфомарции о базе данных. ", response = Status.class, tags={  })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "Кол-во записей в базе данных, включая помеченные как \"удалённые\". ", response = Status.class) })
//
//    @RequestMapping(value = "/service/status",
//        produces = { "application/json" },
//        consumes = { "application/json" },
//        method = RequestMethod.GET)
//    ResponseEntity<Status> status();
//
//}
